AWSTemplateFormatVersion: '2010-09-09'
Description: 'RDS via Cloudformation'

Parameters:
  AllocatedStorage:
    Description: 'Tamanho do storage inicial alocado'
    Type: Number
    Default: '5'
  AllowMajorVersionUpgrade: 
    Description: 'Permite que atualizacoes Major sejam aplicadas no Banco de Dados'
    Type: String
    Default: 'True'
  AutoMinorVersionUpgrade:
    Description: 'Permite que atualizacoes Minor sejam aplicadas no Banco de Dados'
    Type: String
    Default: 'True'
  BackupRetentionPeriod:
    Description: 'Numero de dias que os backups serao retidos automaticamente'
    Type: Number
    Default: 2
  DBInstanceClass:
    Description: 'Capacidade de computacao e memoria'
    Type: String
    Default: 'db.t3.micro'
  DBInstanceIdentifier:
    Description: 'Nome para a Instancia do Banco de Dados'
    Type: String
    Default: 'EC2-Banco-Dados'
  DBName:
    Description: 'Nome do Banco de Dados (precisa estar em minusculo)'
    Type: String
    Default: 'rdsmysql'
  DeleteAutomatedBackups:
    Description: 'Informa se os Backups do Banco de Dados, serao excluidos automaticamente ou nao apos a exclusao dos recursos'
    Type: String
    Default: 'False'
  DeletionProtection:
    Description: 'Habilita a protecao contra exclusao'
    Type: String
    Default: 'False'
  Engine:
    Description: 'Tipo do Banco de Dados'
    Type: String
    Default: 'mysql'
  EngineVersion:
    Description: 'Versao da Engine do Banco de Dados que sera utilizada'
    Type: String
    Default: '8.0.21'
  MasterUsername:
    Description: 'Nome do usuario principal (root) da Instancia'
    Type: String
    Default: 'dbadmin'
  MasterUserPassword:
    Description: 'Senha do usuario principal'
    Type: String
    Default: 'adminmysql'
  MultiAZ:
    Description: 'Define se o Banco de dados sera implementado em varias zonas de disponibilidade ou nao'
    Type: String
    Default: 'False'
  Port:
    Description: 'Numero da porta na qual o Banco de Dados ira aceitar as conexoes'
    Type: Number
    Default: 3306
  PreferredBackupWindow:
    Description: 'Intervalo de tempo que sera usado para criar os backups'
    Type: String
    Default: '01:00-02:45'
  PreferredMaintenanceWindow:
    Description: 'Periodo semanal que podera ocorrer uma manutencao no Banco de Dados'
    Type: String
    Default: 'Mon:03:00-Mon:05:00'
  StorageEncrypted:
    Description: 'Indica se a instancia do Banco de Dados e ou nao criptografada'
    Type: String
    Default: 'True'
  StorageType:
    Description: 'Tipo de armazenamento utilizado na instancia'
    Type: String
    Default: 'standard'

Resources:
  RDInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: !Ref AllocatedStorage
      AllowMajorVersionUpgrade: !Ref AllowMajorVersionUpgrade
      AutoMinorVersionUpgrade: !Ref AutoMinorVersionUpgrade
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      DBInstanceClass: !Ref DBInstanceClass
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBName: !Ref DBName
      DeleteAutomatedBackups: !Ref DeleteAutomatedBackups
      DeletionProtection: !Ref DeletionProtection
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      MultiAZ: !Ref MultiAZ
      Port: !Ref Port
      PreferredBackupWindow: !Ref PreferredBackupWindow
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
      StorageEncrypted: !Ref StorageEncrypted
      StorageType: !Ref StorageType


Outputs:
  RDSInstance:
    Value: !Ref DBName
    Description: 'Banco de Dados Criado'
