AWSTemplateFormatVersion: '2010-09-09'
Description: "RDS via Cloudformation"
Type: AWS::RDS::DBCluster
Parameters:
  AllocatedStorage:
    Description ""
    Type:
    Value:
  AllowMajorVersionUpgrade: 
    Description: ""
    Type:
    Value:
  AutoMinorVersionUpgrade:
    Description: ""
    Type:
    Value:
  AvailabilityZones:
    Description: "xxxxx"
    Type: String
    Value: python3.7
  BackupRetentionPeriod:
    Description: "xxxxx"
    Type: Integer
    Value: python3.7
  DBClusterIdentifier:
    Description: "xxxxx"
    Type: String
    Value: python3.7
  DBInstanceClass:
    Description: ""
    Type:
    Value:
  DBInstanceIdentifier:
    Description: ""
    Type:
    Default:
  DBName:
    Description: ""
    Type: 
    Default:
  DBSubnetGroupName:
    Description: "xxxxx"
    Type: String
    Default: python3.7
  DeleteAutomatedBackups:
    Description: ""
    Type:
    Default:
  DeletionProtection:
    Description: ""
    Type:
    Value:
  EnableCloudwatchLogsExports:
    Description: "xxxxx"
    Type: String
    Value: python3.7
  EnablePerformanceInsights:
    Description: ""
    Type:
    Value:
  Engine:
    Description: "xxxxx"
    Type: String
    Value: python3.7
  EngineVersion:
    Description: "xxxxx"
    Type: String
    Value: python3.7
  KmsKeyId:
    Description: "xxxxx"
    Type: String
    Value: python3.7
  MasterUsername:
    Description: "xxxxx"
    Type: String
    Value: python3.7
  MasterUserPassword:
    Description: "xxxxx"
    Type: String
    Value: python3.7
  MaxAllocatedStorage:
    Description: ""
    Type: 
    Value:
  MultiAZ:
    Description: ""
    Type:
    Value:
  Port:
    Description: "xxxxx"
    Type: Integer
    Value: python3.7
  PreferredBackupWindow:
    Description: "xxxxx"
    Type: String
    Value: python3.7
  PreferredMaintenanceWindow:
    Description: "xxxxx"
    Type: String
    Value: python3.7
  PromotionTier:
    Description: ""
    Type: 
    Value:
  PubliclyAccessible:
    Description: ""
    Type:
    Value: 
  StorageEncrypted:
    Description: ""
    Type: 
    Value:
  StorageType:
    Description: ""
    Type:
    Value:
  Tags:
    - Tag
  VpcSecurityGroupIds:
    Description: "xxxxx"
    Type: String
    Value: python3.7

Resources:
    testelambda:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: !Ref AllocatedStorage
        AllowMajorVersionUpgrade: !Ref AllowMajorVersionUpgrade
        AutoMinorVersionUpgrade: !Ref AutoMinorVersionUpgrade
        AvailabilityZone: !Ref AvailabilityZone
        BackupRetentionPeriod: !Ref BackupRetentionPeriod
        DBClusterIdentifier: !Ref DBClusterIdentifier
        DBInstanceClass: !Ref DBInstanceClass
        DBInstanceIdentifier: !Ref DBInstanceIdentifier
        DBName: !Ref DBName
        DBSubnetGroupName: !Ref DBSubnetGroupName
        DeleteAutomatedBackups: !Ref DeleteAutomatedBackups
        DeletionProtection: !Ref DeletionProtection
        EnableCloudwatchLogsExports: !Ref EnableCloudwatchLogsExports
        EnablePerformanceInsights: !Ref EnablePerformanceInsights
        Engine: !Ref Engine
        EngineVersion: !Ref EngineVersion
        KmsKeyId: !Ref KmsKeyId
        MasterUsername: !Ref MasterUsername
        MasterUserPassword: !Ref MasterUserPassword
        MaxAllocatedStorage: !Ref MaxAllocatedStorage
        MultiAZ: !Ref MultiAZ
        Port: !Ref Port
        PreferredBackupWindow: !Ref PreferredBackupWindow
        PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
        PromotionTier: !Ref PromotionTier
        PubliclyAccessible: !Ref PubliclyAccessible
        StorageEncrypted: !Ref StorageEncrypted
        StorageType: !Ref StorageType
        Tags: !Ref Tags
        VPCSecurityGroups: !Rev VPCSecurityGroups

Outputs:
  DataBase:
    Value: !Ref DBName
    Description: "Banco de Dados Criado"
